### ISSUE TITLE
Clarification of meaning of OED peril codes

### ISSUE THREAD

**Issue by delioma** [OasisLMF/ODS_OpenExposureData#175]
## Description
The peril codes are somewhat confusing, for instance, there is WTC (Tropical Cyclone) and WEC (Extra Tropical Cyclone) described as "no grouped peril code", however it is not clear whether this is wind only. Furthermore, there are additional codes (WW2 and WW1) that are described as Windstorm with and w/o storm surge; and those are described as grouped peril code, which seems to be inconsistent.

**Comment by johcarter** [comment]
After discussion, we propose to update the descriptions of some of the single peril codes to make it more explicit that they  represent the strong wind hazard, and in the case of storm surge, caused by strong wind.

Current descriptions: 
WEC: Extra Tropical Cyclone
WTC: Tropical Cyclone
WSS: Storm Surge

New descriptions:
WEC: Strong wind from Extra Tropical Cyclone
WTC: Strong wind from Tropical Cyclone
WSS: Storm Surge from strong wind

Comments welcome

**Comment by aiste-kalinauskaite** [comment]
This looks a clarification of descriptions only and NOT a change in what the peril codes represent. If so, no objections from my side.
