### ISSUE TITLE
[Marine] Additional Occupancy codes for Marine Cargo and Fine Art

### ISSUE THREAD

**Issue by MattDonovan82** [OasisLMF/ODS_OpenExposureData#204]
## Description

Adding new occupancy codes to support marine cargo to be included in OED v4.0.0
## Reasons for change
 
Supporting the expansion of OED scope to include marino cargo, mainly around storage at ports with a couple of codes for fine art. Cross checks have been made to avoid duplication of existing codes and descriptions.

## Scope of change 
 
- [X] Location File 
- [ ] Accounts File 
- [ ] Reinsurance Scope 
- [ ] Reinsurance Info 

## Impact of change
 
 
These are not breaking changes but will go into the major release of OED v4.0.0 for the inclusion for marine cargo classes

## Data type, default values, are blanks allowed, list valid values

 
Occupancy Codes proposed as below:

In 'Occupancy Values' the Code Range will be 1400-1499 for marine cargo and the Broad Category will be "Marine Cargo" 
In 'Occupancy Values' the Code range will be 1500-1599 for fine art and Broad Category will be "Fine Art"

OED Code | Name | Description
-- | -- | --
1400 | Marine Cargo, Designated Facilities / Vaults | Facilities that are designed and built to store special types of cargo, such as explosives. This often includes higher design criteria or special protection measures for contents located in the facility. Vaults and protected storage for fine arts and specie.
1401 | Marine Cargo, Silo | A tower structure used to store bulk material.
1402 | Marine Cargo, Liquid Tanks | Tanks to store liquid material, usually in the port area.
1403 | Marine Cargo, Gas Tanks | Tanks containing gas material, usually in the port area.
1404 | Marine Cargo, Inside Warehouse at Port | Non-containerized cargoes stored in a warehouse in the port area.
1405 | Marine Cargo, Containerized Inside Warehouse | Containerized cargoes stored in a warehouse in the port area.
1406 | Marine Cargo, Containerized Stacked Outside | Containerized cargoes stored in open areas.
1407 | Marine Cargo, Open Lot or Stockpiled Outside | Non-containerized cargoes stored in open areas.
1408 | Marine Cargo, At Destination in Warehouse | Non-containerized cargoes stored in an inland warehouse.
1409 | Marine Cargo, At Destination Retail | Non-containerized cargoes stored as contents in retail spaces.
1500 | Fine Art, Museums, Institutions, Public Buildings | Fine arts displayed in museums and art institutions.
1501 | Fine Art, Retail & Private Buildings | Fine arts and specie stored in private buildings or in retail spaces.

</html>

**Comment by johcarter** [comment]
@MattDonovan82 please can you attach the text  or excel file containing this table. thanks

**Comment by johcarter** [comment]
Also, @MattDonovan82 can you please confirm that the original Unicede occupancy codes in the v0.06 spec should be brought into the integrated spec as well and is it appropriate to put them in the 'AIR code' column of the OccupancyValues table?

**Comment by MattDonovan82** [comment]
Xls attached as requested @johcarter. As discussed the United codes don't mean anything and so the codes I specified above are the proposed OED codes that fit into the current spec. In regards to the AIR codes in the spec, we should try and go back to complete all of the blanks but this will take some effort and so will be pushed back to a future minor release.

[OED_Marine_Cargo_Data_Spec_v0.0.06.xlsx](https://github.com/user-attachments/files/16179896/OED_Marine_Cargo_Data_Spec_v0.0.06.xlsx)

**Comment by johcarter** [comment]
I've gone with code ranges of 50 rather than 100 to follow the convention for all other occupancy codes, @MattDonovan82 

so Marine Cargo will be in the range 1400-1449 and Fine Art in the range 1450-1499. ok?

OED Code | Name | Description
-- | -- | --
1400 | Marine Cargo, Designated Facilities / Vaults | Facilities that are designed and built to store special types of cargo, such as explosives. This often includes higher design criteria or special protection measures for contents located in the facility. Vaults and protected storage for fine arts and specie.
1401 | Marine Cargo, Silo | A tower structure used to store bulk material.
1402 | Marine Cargo, Liquid Tanks | Tanks to store liquid material, usually in the port area.
1403 | Marine Cargo, Gas Tanks | Tanks containing gas material, usually in the port area.
1404 | Marine Cargo, Inside Warehouse at Port | Non-containerized cargoes stored in a warehouse in the port area.
1405 | Marine Cargo, Containerized Inside Warehouse | Containerized cargoes stored in a warehouse in the port area.
1406 | Marine Cargo, Containerized Stacked Outside | Containerized cargoes stored in open areas.
1407 | Marine Cargo, Open Lot or Stockpiled Outside | Non-containerized cargoes stored in open areas.
1408 | Marine Cargo, At Destination in Warehouse | Non-containerized cargoes stored in an inland warehouse.
1409 | Marine Cargo, At Destination Retail | Non-containerized cargoes stored as contents in retail spaces.
1450 | Fine Art, Museums, Institutions, Public Buildings | Fine arts displayed in museums and art institutions.
1451 | Fine Art, Retail & Private Buildings | Fine arts and specie stored in private buildings or in retail spaces.

**Comment by MattDonovan82** [comment]
yes no problem @johcarter . Moving to done.

**Comment by MattDonovan82** [comment]
closed as followed on in issue (https://github.com/OasisLMF/ODS_OpenExposureData/issues/210)
