### ISSUE TITLE
Additional OED Codes 

### ISSUE THREAD

**Issue by MattDonovan82** [OasisLMF/ODS_OpenExposureData#68]
GC are proposing the additional codes for Occupancy, Roofcover and Geogscheme to be included into OED:

Geogschemes: UPRN -  UK Property reference number (created by Ordnance Survey)
                          EIRCODE - For Republic of Ireland

Roofcover: 26 - Thatch
                   27 - Felt
                   28 - Zinc

Occ codes: 1070 - Residential, Detached house
                    1071 - Residential, Semi-detached house. Attached residential unit. Shares a single common party wall, common type           in UK/Ireland.
                     1072 - Residential, end terrace house. Attached residential unit. Used for end of row houses with additional end gable exposure to wind
                     1073 - Residential, Bungalow. Detached residential unit. One story, often with dormer roof. For semi-detached and terraced bungalows use those codes with single storey coding.

**Comment by MattDonovan82** [comment]
I don't see any issues with these, except whether the proposed 1070 code for "detached house" would fall under the current 1051 for 'Residential, Permanent dwelling: single-family' which specifies "detached dwellings" in the description.
--

**Comment by MattDonovan82** [comment]
@carlholden can you review this?

**Comment by MattDonovan82** [comment]
Thanks @PaulLDJones. We generally want to avoid duplication but as you state, this is for specific detached properties so should differentiate enough. 

Thoughts @aiste-kalinauskaite @jones-matt @johcarter @benhayes21

**Comment by johcarter** [comment]
Hi @MattDonovan82 you raise a good point about duplication from the model developer perspective. Both 1051 and 1070 would be valid choices to describe a single detached house, say, and you could have some models that prefer to use the new 1070 codes because the extra detail is important for the modelling of risk (say for flood), and other models use the existing code 1051. Leading to different codes needed in exposure inputs for different models, which could get messy.

I suggest adding to the description of 1051  - "unknown property type" to encourage people to use the new codes where the property type is known.

For models where the property type is not relevant to vulnerability, map new 107X codes and 105X codes to the same vulnerability type.

For models where the property type is relevant to vulnerability, use the new 107X codes and map 1051 to a "property type unknown" vulnerability, ie a whatever the suitable default is.

**Comment by MattDonovan82** [comment]
ok great. This would then make a better option? @PaulLDJones

**Comment by PaulLDJones** [comment]
@johcarter @MattDonovan82 this is known and we looked at it. However for translation bewteen differning modelling vendor codes (external to OASIS) this makes the process cumbersome with some models holding specific occupcancies and some models using combinations of occupancy and building type. To a certain extent the extra building type field is a bit of a duplicate of occupancy.

**Comment by johcarter** [comment]
In view of that, I think extending the OED codes to include building types will make it easier for conversions into OED, lead to better information about exposures used by models. I would suggest deprecating BuildingType.

**Comment by MattDonovan82** [comment]
@PaulLDJones in the interest of clarity, for occ code 1073 (bungalows), when you say "use those codes with single story coding", I assume you mean that when coding a semi-detached bungalow for example, it would be coded as occ code 1071 but with '1' **NumberOfStoreys**?

**Comment by MattDonovan82** [comment]
@PaulLDJones please review the attached - changes highlighted in yellow in 'Occupancy Values' and 'Other Values' tab. Please add any examples for the new geogschemes. Thanks.
[OpenExposureData_Spec_edit_MD.xlsx](https://github.com/OasisLMF/OpenDataStandards/files/8919176/OpenExposureData_Spec_edit_MD.xlsx)

**Comment by PaulLDJones** [comment]
Matt

Yes, it’s about the roof form and common walls rather than the height as the primary descriptor.

Regards



Paul Jones, Head of UK Client Data Services, Global Strategic Advisory


Guy Carpenter | Global Strategic Advisory
Tower Place, London, EC3R 5BU

+44 (0)20 7357 3640 | +44 (0)7392 122023 | ***@***.******@***.***>
***@***.***

A business of Marsh McLennan


The data and analysis provided by Guy Carpenter herein or in connection herewith are provided as is, without warranty of any kind whether express or implied. Neither Guy Carpenter, its affiliates nor their officers, directors, agents, modelers, or subcontractors (collectively, Providers) guarantee or warrant the correctness, completeness, currentness, merchantability, or fitness for a particular purpose of such data and analysis. In no event will any Provider be liable for loss of profits or any other indirect, special, incidental and/or consequential damage of any kind howsoever incurred or designated, arising from any use of the data and analysis provided herein or in connection herewith

**Comment by carlholden** [comment]
Hi all,

Interesting thread - from a modelling pov, a bungalow should always be 1 storey of course, but can also be detached and semi-detached as well (and let’s not ignore loft conversions!). My guess is there may not be a perfect solution, its just a case of how model developers build the vulnerabilities as well as how cat modellers code up exposure information etc., and matching the two.

Hope that’s helpful.

Thanks,

Carl

On 16 Jun 2022, at 14:21, PaulLDJones ***@***.***> wrote:

﻿
Matt 

Yes, it’s about the roof form and common walls rather than the height as the primary descriptor. 

Regards 



Paul Jones, Head of UK Client Data Services, Global Strategic Advisory 


Guy Carpenter | Global Strategic Advisory 
Tower Place, London, EC3R 5BU 

+44 (0)20 7357 3640 | +44 (0)7392 122023 | ***@***.******@***.***> 
***@***.*** 

A business of Marsh McLennan 


The data and analysis provided by Guy Carpenter herein or in connection herewith are provided as is, without warranty of any kind whether express or implied. Neither Guy Carpenter, its affiliates nor their officers, directors, agents, modelers, or subcontractors (collectively, Providers) guarantee or warrant the correctness, completeness, currentness, merchantability, or fitness for a particular purpose of such data and analysis. In no event will any Provider be liable for loss of profits or any other indirect, special, incidental and/or consequential damage of any kind howsoever incurred or designated, arising from any use of the data and analysis provided herein or in connection herewith

**Comment by jones-matt** [comment]
In terms of the building type occupancy changes I think that adding in duplication / suggesting the deprecation of BuildingType is a large enough change to warrant Steering Group comment as model developers and users may already be be using BuildingType. 

The number of occupancy codes added is less than the number of BuildingType codes so are we happy to lose the extra codes? Do we need a specific bungalow occupancy given that NumberOfStoreys can be used?

**Comment by MattDonovan82** [comment]
As there is now a separate occ code for "end-terrace house" (occ code 1072), its less ambiguous and clearer if the current occ code for "terraced-housing (occ code 1056) is re-named to be "Residential, Mid-Terraced Housing" with the following description:

Attached residential unit, not end of terrace (use separate code 1072). Also referred to as townhouses, row houses, row homes, or brownstones. Usually more than one story and built close to the street.

This way there are now two separate codes for 'mid -terrace' and 'end of terrace' and the 'building types' for both of these will be removed.

**Comment by MattDonovan82** [comment]
closed as included in OED v3.0.0
