### ISSUE TITLE
Additions to OED for offshore renewable energy

### ISSUE THREAD

**Issue by MattDonovan82** [OasisLMF/ODS_OpenExposureData#81]
We have had a proposal to update the OED spec to account for offshore renewables. Please see attached for the new proposed Input Fields and Construction/Occupancy Values.

I've had a look at what's already covered in OED for offshore and these additions do not seem to be duplications as there isn't much on specifics of renewable offshore currently in OED
[OpenExposureData_Spec-Offshore Proposal 220812.xlsx](https://github.com/OasisLMF/OpenDataStandards/files/9316747/OpenExposureData_Spec-Offshore.Proposal.220812.xlsx)

@johcarter @jones-matt @benhayes21

**Comment by maegic73** [comment]
It could be useful to also support coverage types Operator's Extra Expense (OEE) and Removal of Debris (RoW) for offshore (renewable) assets. Maybe this is taken care of already or an overkill, but I thought I better mention.

**Comment by johcarter** [comment]
No we don't have these coverages yet @maegic73. Do they tend to be modelled separately, or are the payouts somehow dependent on the primary structure loss? (For example, extra expenses = 10% of the structure loss).  OED supports an extra expense element for step policies in the account file but they are not included as a TIV coverage like buildings, other, contents, time because payout is expressed relative to the loss on the primary coverage.  

Regarding the proposals, I think perhaps the input field names. 'WaterDepth', 'Length', 'Capacity' might benefit from being more descriptive depending on how broadly useful they are? some ideas 'LineLength, SectionLength, PowerCapacity, OffshoreWaterDepth (if there is no other context other than offshore).  And we could also have fields to specify units where it could vary, eg WaterDepthUnits, LengthUnits, CapacityUnits.

**Comment by maegic73** [comment]
Thanks Jo. How I've seen it this would be a separate ('primary') coverage, i.e. defined with the client with its own sum insured and own conditions (deductible/limits/shares), in addition to PD and BI. Not being a offshore market person, I don't want to overdo this, but thought I place the comment for if easy to implement or affirmed by others.

**Comment by MattDonovan82** [comment]
updates to the proposed names and descriptions attached (highlighted in yellow) and some further comments:
[issue_81_updates.xlsx](https://github.com/OasisLMF/OpenDataStandards/files/9505527/issue_81_updates.xlsx)

* Updated OED Input Fields to: SectionLength, PowerCapacity, OffshoreWaterDepth and updated descriptions.

* Removed offshore hydrogen as an occupancy for now, as most of the hydrogen generating assets proposed are going to be linked with one form of power generation and for the foreseeable future, also co-located on the same platform as the offshore substation
 
OEE and ROW:
Its expected that OEE and ROW are usually part of and not in addition to the separately declared loss limit (or Sum Insured as the case may be). This is not always the case though and sometimes these are not part of and therefore in addition – this is particularly the case for Sue and Labour and ROW and when the loss limit is small relative to how quickly offshore costs for ROW can escalate. We would propose that we assume the former at this stage.
 
For the Removal of Debris (RoW), in the context of operational phase events: This is difficult to quantify and we would expect to see this simplified as a percentage of property damage.
 
So for OEE and ROW, we would propose that they are not modelled as a separate cover at this stage.

**Comment by MattDonovan82** [comment]
I've added 0 modifiers to represent unknown for the following:

* Anchorage
* Diameter of Pipeline
* Voltage of Energy
* Pumping Capacity

**Comment by MattDonovan82** [comment]
Closed as included in OED v3.0.0
